name: travel_on_final
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  go_router: ^14.3.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  table_calendar: ^3.1.2
  flutter_naver_map: ^1.3.0+1
  http: ^1.2.2
  url_launcher: ^6.3.1
  easy_localization: ^3.0.7

  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.4.1
  flutter_dotenv: ^5.2.1

  tosspayments_widget_sdk_flutter: 2.0.0
  get: ^4.6.6

  # 권한
  permission_handler: ^11.3.1

  #firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.2
  firebase_app_check: ^0.3.1+5
  firebase_messaging: ^15.1.4
  flutter_local_notifications: ^18.0.1
  timeago: ^3.7.0
  google_sign_in: ^6.2.2
  kakao_flutter_sdk_user: ^1.9.6
  flutter_native_splash: ^2.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  fake_cloud_firestore: ^3.1.0
  build_runner: ^2.4.8

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
    - test/assets/translations/
    - .env
